services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: directus
      POSTGRES_USER: directus
      POSTGRES_PASSWORD_FILE: /run/secrets/directus_db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - directus_db_password

  directus:
    image: directus/directus:latest
    restart: always
    ports:
      - 8055:8055
    depends_on:
      - db
    environment:
      KEY_FILE: /run/secrets/directus_key
      SECRET_FILE: /run/secrets/directus_secret
      DB_CLIENT: pg
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD_FILE: /run/secrets/directus_db_password
    secrets:
      - directus_key
      - directus_secret
      - directus_db_password

  web:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64  # ✅ runs native on M1/M2/M3/M4 and Ubuntu on Parallels
    ports:
      - "3000:80"
    depends_on:
      - directus
    volumes:
      - ./public:/usr/share/nginx/html:ro

volumes:
  pgdata:

secrets:
  directus_key:
    file: ./secrets/directus_key.txt
  directus_secret:
    file: ./secrets/directus_secret.txt
  directus_db_password:
    file: ./secrets/db_password.txt
