---
- name: Copy Directus systemd service
  ansible.builtin.copy:
    src: scripts/directus-stack.service
    dest: /etc/systemd/system/directus-stack.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start Directus stack service
  ansible.builtin.systemd:
    name: directus-stack
    enabled: true
    state: restarted
